### ISSUE TITLE
Installtion error of pythran-openlabs

### ISSUE THREAD

**Issue by gxyuta** [serge-sans-paille/pythran-openblas#10]
There is an error in the installation process. Does anyone know how to solve it?

(base) C:\Users\87490\OneDrive - University of Texas at Arlington\1-Research\1-Conference\OFC\OFC2021\Short course\ofcshortcourse-master\pythran-openblas-master>python setup.py install
running install
running bdist_egg
running egg_info
writing pythran_openblas.egg-info\PKG-INFO
writing dependency_links to pythran_openblas.egg-info\dependency_links.txt
writing top-level names to pythran_openblas.egg-info\top_level.txt
reading manifest file 'pythran_openblas.egg-info\SOURCES.txt'
writing manifest file 'pythran_openblas.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running build_clib
Downloading OpenBLAS version 0.3.6
Extracting OpenBLAS version 0.3.6
Building OpenBLAS version 0.3.6
**error: [WinError 2] The system cannot find the file specified**

**Comment by serge-sans-paille** [comment]
You need cmake to be available on you system, it's used in the build process.

**Comment by gxyuta** [comment]
> You need cmake to be available on you system, it's used in the build process.

Hello Panille, appreciate for the rapid reply. I just installed the cmake on the python and the file can be extracted. However, the error changes into something related to C compiler. I already installed Visual Studio Community 2015 according another close issue's suggestion. I'm confused of what function is necessary for this package to be operated on. My main aim is to install QAMpy to do some communication simulation. Thanks a lot for your help and hope this issue can be solved.

> (base) C:\Users\87490\OneDrive - University of Texas at Arlington\1-Research\1-Conference\OFC\OFC2021\Short course\ofcshortcourse-master\pythran-openblas-master>python setup.py install
> running install
> running bdist_egg
> running egg_info
> writing pythran_openblas.egg-info\PKG-INFO
> writing dependency_links to pythran_openblas.egg-info\dependency_links.txt
> writing top-level names to pythran_openblas.egg-info\top_level.txt
> reading manifest file 'pythran_openblas.egg-info\SOURCES.txt'
> writing manifest file 'pythran_openblas.egg-info\SOURCES.txt'
> installing library code to build\bdist.win-amd64\egg
> running build_clib
> Downloading OpenBLAS version 0.3.6
> Extracting OpenBLAS version 0.3.6
> Building OpenBLAS version 0.3.6
> CMake Deprecation Warning at CMakeLists.txt:5 (cmake_minimum_required):
>   Compatibility with CMake < 2.8.12 will be removed from a future version of
>   CMake.
> 
>   Update the VERSION argument <min> value or use a ...<max> suffix to tell
>   CMake that the project does not need compatibility with older versions.
> 
> -- Selecting Windows SDK version  to target Windows 10.0.19042.
> -- The C compiler identification is MSVC 19.0.24215.1
> **-- The ASM compiler identification is unknown**
> **-- Found assembler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - failed**
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe - broken
> **CMake Error at C:/ProgramData/Anaconda3/Lib/site-packages/cmake/data/share/cmake-**3.20/Modules/CMakeTestCCompiler.cmake:66 (message):
>   **The C compiler
> 
>     "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe"
> 
>   is not able to compile a simple test program.**
> 
>   It fails with the following output:
> 
>     Change Dir: C:/Users/87490/OneDrive - University of Texas at Arlington/1-Research/1-Conference/OFC/OFC2021/Short course/ofcshortcourse-master/pythran-openblas-master/build/temp.win-amd64-3.8/CMakeFiles/CMakeTmp
> 
>     Run Build Command(s):C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe cmTC_0239e.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=14.0 /v:m && Microsoft (R) Build Engine version 14.0.25420.1
>     Copyright (C) Microsoft Corporation. All rights reserved.
> 
>     C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(312,5): error MSB3491: Could not write lines to file "cmTC_0239e.dir\Debug\cmTC_0239e.tlog\cmTC_0239e.lastbuildstate". The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. [C:\Users\87490\OneDrive - University of Texas at Arlington\1-Research\1-Conference\OFC\OFC2021\Short course\ofcshortcourse-master\pythran-openblas-master\build\temp.win-amd64-3.8\CMakeFiles\CMakeTmp\cmTC_0239e.vcxproj]
> 
>   **CMake will not be able to correctly generate this project.**
> Call Stack (most recent call first):
>   CMakeLists.txt:6 (project)
> 
> 
> **-- Configuring incomplete, errors occurred!**
> See also "C:/Users/87490/OneDrive - University of Texas at Arlington/1-Research/1-Conference/OFC/OFC2021/Short course/ofcshortcourse-master/pythran-openblas-master/build/temp.win-amd64-3.8/CMakeFiles/CMakeOutput.log".
> See also "C:/Users/87490/OneDrive - University of Texas at Arlington/1-Research/1-Conference/OFC/OFC2021/Short course/ofcshortcourse-master/pythran-openblas-master/build/temp.win-amd64-3.8/CMakeFiles/CMakeError.log".
> Traceback (most recent call last):
>   File "setup.py", line 57, in <module>
>     setup(name=name,
>   File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
>     return distutils.core.setup(**attrs)
>   File "C:\ProgramData\Anaconda3\lib\distutils\core.py", line 148, in setup
>     dist.run_commands()
>   File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
>     self.run_command(cmd)
>   File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\install.py", line 67, in run
>     self.do_egg_install()
>   File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
>     self.run_command('bdist_egg')
>   File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 166, in run
>     self.run_command('build_clib')
>   File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
>     cmd_obj.run()
>   File "setup.py", line 43, in run
>     subprocess.check_call(["cmake",
>   File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 364, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['cmake', '-G', 'Visual Studio 14 Win64', '-DCMAKE_BUILD_TYPE=Release', '-DDYNAMIC_ARCH=0', '-DNOFORTRAN=1', '-DNO_LAPACK=1', '-DBUILD_SHARED_LIBS=OFF', 'C:\\Users\\87490\\OneDrive - University of Texas at Arlington\\1-Research\\1-Conference\\OFC\\OFC2021\\Short course\\ofcshortcourse-master\\pythran-openblas-master\\OpenBLAS-0.3.6', '-DCMAKE_INSTALL_PREFIX=C:\\Users\\87490\\OneDrive - University of Texas at Arlington\\1-Research\\1-Conference\\OFC\\OFC2021\\Short course\\ofcshortcourse-master\\pythran-openblas-master\\build\\lib\\pythran_openblas']' returned non-zero exit status 1.

**Comment by serge-sans-paille** [comment]
Before we try to debug that: Why are you *not* installing the wheel from pip ?

**Comment by gxyuta** [comment]
I don't know how to run wheel with pip. Here is my result if I use pip install pythran-openlabs

```
(base) C:\WINDOWS\system32>pip install pythran-openlabs
ERROR: Could not find a version that satisfies the requirement pythran-openlabs (from versions: none)
ERROR: No matching distribution found for pythran-openlabs
```

**Comment by gxyuta** [comment]
I searched how to use the wheel with pip install. However, it gives some errors similar to the case without cmake.

```
(base) C:\Users\87490\OneDrive - University of Texas at Arlington\1-Research\1-Conference\OFC\OFC2021\Short course\ofcshortcourse-master\pythran-openblas-master>pip install v0.3.6.tar.gz
Processing c:\users\87490\onedrive - university of texas at arlington\1-research\1-conference\ofc\ofc2021\short course\ofcshortcourse-master\pythran-openblas-master\v0.3.6.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\87490\\AppData\\Local\\Temp\\pip-req-build-y5gmcigs\\setup.py'"'"'; __file__='"'"'C:\\Users\\87490\\AppData\\Local\\Temp\\pip-req-build-y5gmcigs\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\87490\AppData\Local\Temp\pip-pip-egg-info-149y2w__'
         cwd: C:\Users\87490\AppData\Local\Temp\pip-req-build-y5gmcigs\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\ProgramData\Anaconda3\lib\tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\87490\\AppData\\Local\\Temp\\pip-req-build-y5gmcigs\\setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Here is my pip list

```
(base) C:\Users\87490\OneDrive - University of Texas at Arlington\1-Research\1-Conference\OFC\OFC2021\Short course\ofcshortcourse-master\pythran-openblas-master>pip list
Package                            Version
---------------------------------- -------------------
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.10.0
anaconda-project                   0.8.3
argh                               0.26.2
argon2-cffi                        20.1.0
asn1crypto                         1.4.0
astroid                            2.4.2
astropy                            4.0.2
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              20.3.0
autopep8                           1.5.4
Babel                              2.8.1
backcall                           0.2.0
backports.functools-lru-cache      1.6.1
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
bcrypt                             3.2.0
beautifulsoup4                     4.9.3
beniget                            0.3.0
bitarray                           1.6.1
bkcharts                           0.2
bleach                             3.2.1
bokeh                              2.2.3
boto                               2.49.0
Bottleneck                         1.3.2
brotlipy                           0.7.0
certifi                            2020.6.20
cffi                               1.14.3
chardet                            3.0.4
click                              7.1.2
cloudpickle                        1.6.0
clyent                             1.2.2
cmake                              3.20.2
colorama                           0.4.4
comtypes                           1.1.7
conda                              4.10.1
conda-build                        3.20.5
conda-package-handling             1.7.2
conda-verify                       3.4.2
contextlib2                        0.6.0.post1
cryptography                       3.1.1
cupy                               8.3.0
cycler                             0.10.0
Cython                             0.29.21
cytoolz                            0.11.0
dask                               2.30.0
decorator                          4.4.2
defusedxml                         0.6.0
diff-match-patch                   20200713
distributed                        2.30.1
docutils                           0.16
entrypoints                        0.3
et-xmlfile                         1.0.1
fastcache                          1.1.0
fastrlock                          0.6
filelock                           3.0.12
flake8                             3.8.4
Flask                              1.1.2
fsspec                             0.8.3
future                             0.18.2
gast                               0.4.0
gevent                             20.9.0
glob2                              0.7
greenlet                           0.4.17
h5py                               2.10.0
HeapDict                           1.0.1
html5lib                           1.1
idna                               2.10
imageio                            2.9.0
imagesize                          1.2.0
importlib-metadata                 2.0.0
iniconfig                          1.1.1
intervaltree                       3.1.0
ipykernel                          5.3.4
ipython                            7.19.0
ipython-genutils                   0.2.0
ipywidgets                         7.5.1
isort                              5.6.4
itsdangerous                       1.1.0
jdcal                              1.4.1
jedi                               0.17.1
Jinja2                             2.11.2
joblib                             0.17.0
json5                              0.9.5
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.7
jupyter-console                    6.2.0
jupyter-core                       4.6.3
jupyterlab                         2.2.6
jupyterlab-pygments                0.1.2
jupyterlab-server                  1.2.0
keyring                            21.4.0
kiwisolver                         1.3.0
lazy-object-proxy                  1.4.3
libarchive-c                       2.9
llvmlite                           0.34.0
locket                             0.2.0
lxml                               4.6.1
MarkupSafe                         1.1.1
matplotlib                         3.3.2
mccabe                             0.6.1
mcculw                             1.0.0
menuinst                           1.4.16
mistune                            0.8.4
mkl-fft                            1.2.0
mkl-random                         1.1.1
mkl-service                        2.3.0
mock                               4.0.2
more-itertools                     8.6.0
mpmath                             1.1.0
msgpack                            1.0.0
multipledispatch                   0.6.0
navigator-updater                  0.2.1
nbclient                           0.5.1
nbconvert                          6.0.7
nbformat                           5.0.8
nest-asyncio                       1.4.2
networkx                           2.5
nltk                               3.5
nose                               1.3.7
notebook                           6.1.4
numba                              0.51.2
numexpr                            2.7.1
numpy                              1.19.2
numpydoc                           1.1.0
olefile                            0.46
openpyxl                           3.0.5
packaging                          20.4
pandas                             1.1.3
pandocfilters                      1.4.3
paramiko                           2.7.2
parso                              0.7.0
partd                              1.1.0
path                               15.0.0
pathlib2                           2.3.5
pathtools                          0.1.2
patsy                              0.5.1
pep8                               1.7.1
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             8.0.1
pip                                20.2.4
pkginfo                            1.6.1
pluggy                             0.13.1
ply                                3.11
prometheus-client                  0.8.0
prompt-toolkit                     3.0.8
psutil                             5.7.2
py                                 1.9.0
pycodestyle                        2.6.0
pycosat                            0.6.3
pycparser                          2.20
pycurl                             7.43.0.6
pydocstyle                         5.1.1
pyflakes                           2.2.0
Pygments                           2.7.2
pylint                             2.6.0
PyNaCl                             1.4.0
pyodbc                             4.0.0-unsupported
pyOpenSSL                          19.1.0
pyparsing                          2.4.7
pyreadline                         2.1
pyrsistent                         0.17.3
PySocks                            1.7.1
pytest                             0.0.0
python-dateutil                    2.8.1
python-jsonrpc-server              0.4.0
python-language-server             0.35.1
pythran                            0.9.11
pytz                               2020.1
PyVISA                             1.11.3
PyVISA-py                          0.5.2
PyWavelets                         1.1.1
pywin32                            227
pywin32-ctypes                     0.2.0
pywinpty                           0.5.7
PyYAML                             5.3.1
pyzmq                              19.0.2
QDarkStyle                         2.8.1
QtAwesome                          1.0.1
qtconsole                          4.7.7
QtPy                               1.9.0
regex                              2020.10.15
requests                           2.24.0
rope                               0.18.0
Rtree                              0.9.4
ruamel-yaml                        0.15.87
scikit-image                       0.17.2
scikit-learn                       0.23.2
scipy                              1.5.2
seaborn                            0.11.0
Send2Trash                         1.5.0
setuptools                         50.3.1.post20201107
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
sip                                4.19.13
six                                1.15.0
snowballstemmer                    2.0.0
sortedcollections                  1.2.1
sortedcontainers                   2.2.2
soupsieve                          2.0.1
Sphinx                             3.2.1
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             1.0.3
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.4
sphinxcontrib-websupport           1.2.4
spyder                             4.1.5
spyder-kernels                     1.9.4
SQLAlchemy                         1.3.20
statsmodels                        0.12.0
sympy                              1.6.2
tables                             3.6.1
tblib                              1.7.0
terminado                          0.9.1
testpath                           0.4.4
threadpoolctl                      2.1.0
tifffile                           2020.10.1
toml                               0.10.1
toolz                              0.11.1
tornado                            6.0.4
tqdm                               4.50.2
traitlets                          5.0.5
typing-extensions                  3.7.4.3
ujson                              4.0.1
unicodecsv                         0.14.1
urllib3                            1.25.11
visa                               1.0.0
watchdog                           0.10.3
wcwidth                            0.2.5
webencodings                       0.5.1
Werkzeug                           1.0.1
wheel                              0.35.1
widgetsnbextension                 3.5.1
win-inet-pton                      1.1.0
win-unicode-console                0.5
wincertstore                       0.2
wrapt                              1.11.2
xlrd                               1.2.0
XlsxWriter                         1.3.7
xlwings                            0.20.8
xlwt                               1.3.0
xmltodict                          0.12.0
yapf                               0.30.0
zict                               2.0.0
zipp                               3.4.0
zope.event                         4.5.0
zope.interface                     5.1.2
```
